FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL
ARG VITE_DEBUG_ROLE_PICKER
ENV VITE_DEBUG_ROLE_PICKER=$VITE_DEBUG_ROLE_PICKER

RUN npm run build

FROM alpine:latest

WORKDIR /var/www/html

COPY --from=builder /app/dist .
